# This is a basic workflow to help you get started with Actions

name: publish

on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Run install pnpm
        run: npm i -g pnpm

      - name: Run install
        run: pnpm install

      - name: Run build
        run: pnpm build:lib

      - name: Run test
        run: pnpm test

      - name: Run publish
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
