# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run install pnpm
        run: npm i -g pnpm

      - name: Run install
        run: npm i -g lerna && lerna bootstrap --hoist
        
      - name: Run test
        run: lerna test
      - name: Run codecov
        run: npx codecov --token=${{ secrets.CODECOV_TOKEN }}
